eco<- readRDS('data_raw/eco.RDS') |> as.data.frame()
Norms2010 <- readRDS('data_raw/Norms2010.RDS')
usethis::use_data(eco, overwrite = T)
usethis::use_data(Norms2010, overwrite = T)
library(terra)
  tintercept <- rast('data_raw/tintercept.tif')
  xyr <- rast(nrows=180, ncols=360, nlyrs=1, crs=crs('EPSG:4326'), extent=ext(-180,180,-90,90), vals=1)
  tintercept <- (tintercept) |> as.data.frame(xy=T)
  tintercept2 <- rasterize(tintercept[,c('x','y')], xyr, values=tintercept$lyr1)
  usethis::use_data(tintercept, overwrite = T)
plot(tintercept2)
